// Mocks generated by Mockito 5.4.4 from annotations
// in news_flutter_data_newsapi/test/api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_flutter_data_newsapi/api_service.dart' as _i3;
import 'package:news_flutter_data_newsapi/entity/news_response_entity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNewsResponseEntity_0 extends _i1.SmartFake implements _i2.NewsResponseEntity {
  _FakeNewsResponseEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  @override
  _i4.Future<_i2.NewsResponseEntity> everything({
    required String? q,
    required String? from,
    required String? sortBy,
    required String? apiKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #everything,
          [],
          {
            #q: q,
            #from: from,
            #sortBy: sortBy,
            #apiKey: apiKey,
          },
        ),
        returnValue: _i4.Future<_i2.NewsResponseEntity>.value(_FakeNewsResponseEntity_0(
          this,
          Invocation.method(
            #everything,
            [],
            {
              #q: q,
              #from: from,
              #sortBy: sortBy,
              #apiKey: apiKey,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.NewsResponseEntity>.value(_FakeNewsResponseEntity_0(
          this,
          Invocation.method(
            #everything,
            [],
            {
              #q: q,
              #from: from,
              #sortBy: sortBy,
              #apiKey: apiKey,
            },
          ),
        )),
      ) as _i4.Future<_i2.NewsResponseEntity>);
}
